# Sources
DIR_SOURCES := aural.c background.c border_outline.c boxsizing.c font.c generated_list.c margin.c padding.c page.c positioning.c properties.c text.c utils.c

include build/makefiles/Makefile.subdir
